# Generated by Django 5.2.10 on 2026-03-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='posts/'),
        ),
    ]
